name: "Build + Publish wasm version"
description: "Build wasm and publish to github pages"
author: "axel.paulander@gmail.com"

runs:
    using: "docker"
    image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"